name: Update

on:
  schedule:
    - cron: '0 */19 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-24.04
    name: Run
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Remove README.md
        run: |
          sudo rm -f README.md
          sleep_time=$((RANDOM % 400))
          sleep $sleep_time
          echo "Last updated on $(TZ='Asia/Singapore' date)" > README.md

      - name: Commit and Push Changes
        run: |
            git add README.md
            git config --local user.name "GitHub Action"
            git config --local user.email "action@github.com"
            git commit -m "Updated README on $(TZ='Asia/Singapore' date "+%Y/%m/%d %H:%M:%S")"
            git push origin main --force
